language: ruby
rvm:
  - 2.3.1
# script:
#   - RAILS_ENV=test bin/rails db:migrate --trace
#   - bundle exec rspec spec/
addons:
    code_climate:
        repo_token: 85b4051e5cc63da41e0263446cb5fcd34824986d8b1ca2c8cbf92732d43225da
