require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BucketlistsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Bucketlist. As you add validations to Bucketlist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BucketlistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bucketlists as @bucketlists" do
      bucketlist = Bucketlist.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:bucketlists)).to eq([bucketlist])
    end
  end

  describe "GET #show" do
    it "assigns the requested bucketlist as @bucketlist" do
      bucketlist = Bucketlist.create! valid_attributes
      get :show, params: {id: bucketlist.to_param}, session: valid_session
      expect(assigns(:bucketlist)).to eq(bucketlist)
    end
  end

  describe "GET #new" do
    it "assigns a new bucketlist as @bucketlist" do
      get :new, params: {}, session: valid_session
      expect(assigns(:bucketlist)).to be_a_new(Bucketlist)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bucketlist as @bucketlist" do
      bucketlist = Bucketlist.create! valid_attributes
      get :edit, params: {id: bucketlist.to_param}, session: valid_session
      expect(assigns(:bucketlist)).to eq(bucketlist)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Bucketlist" do
        expect {
          post :create, params: {bucketlist: valid_attributes}, session: valid_session
        }.to change(Bucketlist, :count).by(1)
      end

      it "assigns a newly created bucketlist as @bucketlist" do
        post :create, params: {bucketlist: valid_attributes}, session: valid_session
        expect(assigns(:bucketlist)).to be_a(Bucketlist)
        expect(assigns(:bucketlist)).to be_persisted
      end

      it "redirects to the created bucketlist" do
        post :create, params: {bucketlist: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Bucketlist.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bucketlist as @bucketlist" do
        post :create, params: {bucketlist: invalid_attributes}, session: valid_session
        expect(assigns(:bucketlist)).to be_a_new(Bucketlist)
      end

      it "re-renders the 'new' template" do
        post :create, params: {bucketlist: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bucketlist" do
        bucketlist = Bucketlist.create! valid_attributes
        put :update, params: {id: bucketlist.to_param, bucketlist: new_attributes}, session: valid_session
        bucketlist.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bucketlist as @bucketlist" do
        bucketlist = Bucketlist.create! valid_attributes
        put :update, params: {id: bucketlist.to_param, bucketlist: valid_attributes}, session: valid_session
        expect(assigns(:bucketlist)).to eq(bucketlist)
      end

      it "redirects to the bucketlist" do
        bucketlist = Bucketlist.create! valid_attributes
        put :update, params: {id: bucketlist.to_param, bucketlist: valid_attributes}, session: valid_session
        expect(response).to redirect_to(bucketlist)
      end
    end

    context "with invalid params" do
      it "assigns the bucketlist as @bucketlist" do
        bucketlist = Bucketlist.create! valid_attributes
        put :update, params: {id: bucketlist.to_param, bucketlist: invalid_attributes}, session: valid_session
        expect(assigns(:bucketlist)).to eq(bucketlist)
      end

      it "re-renders the 'edit' template" do
        bucketlist = Bucketlist.create! valid_attributes
        put :update, params: {id: bucketlist.to_param, bucketlist: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bucketlist" do
      bucketlist = Bucketlist.create! valid_attributes
      expect {
        delete :destroy, params: {id: bucketlist.to_param}, session: valid_session
      }.to change(Bucketlist, :count).by(-1)
    end

    it "redirects to the bucketlists list" do
      bucketlist = Bucketlist.create! valid_attributes
      delete :destroy, params: {id: bucketlist.to_param}, session: valid_session
      expect(response).to redirect_to(bucketlists_url)
    end
  end

end
